config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'tap' => 'static_pages#taptapfront'
  get 'live' => 'static_pages#live_update'
  get 'nfc' => 'static_pages#nfc'
  get 'checkin/:id' => 'static_pages#checkin'
  root 'static_pages#home'
  post 'users' => 'static_pages#home'
  get 'refresh' => 'static_pages#refresh'
  get 'sort_date' => 'static_pages#sort_by_changed_date'
  get 'sort_status'=> 'static_pages#sort_by_status'
  get 'sort_name' => 'static_pages#sort_by_name'

end

app/models/update.rb
class Update < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	scope :sorted_by_status, -> {order(:status)}
	scope :last_updated, ->{order(updated_at: :desc)}
	scope :sort_by_name, ->{order(:name)}
end
public
def update_db
    EventbriteAPI::Configuration.access_token=ENV['ACCESS_KEY']
    @eb = EventbriteAPI.new
    @event = @eb.events(id:ENV['EVENT'])
    if Update.count < 1
      print "YOOOOOOOOOOOOOHOOOOOOOOOOOOOOOOOOO"
      @time = "2010-11-12T7:23:03Z"
      update = Update.new
      update.time = Time.now
      update.save
    else
      @time = Update.first.time.strftime("%Y-%m-%dT%H:%M:%SZ")
      Update.first.update_attribute(:time, Time.now)
    end
    print "HELOOOOOOOOOOOOOOOOOOOO" + @time
    page_count = @event.attendees(status:"attending",changed_since:@time).get.body["pagination"]["page_count"]
    for i in 1..page_count
      @attendees = @event.attendees(status:"attending",page:i,changed_since:@time).get.body["attendees"]
      @attendees.each do |test| 
        unless user = User.find_by(name: test["profile"]["name"])
          user = User.new
          user.name = test["profile"]["name"]
          user.email = test["profile"]["email"]
          user.status = test["barcodes"].first["status"]
          user.card_no = test["answers"].find{ |h| h["question_id"]=="8754207" }["answer"]
          user.student_id = test["answers"].find{ |h| h["question_id"]=="8693425" }["answer"]
          user.save
        else
          #if test["barcodes"].first["status"] == 'used' && user.status == 'unused'
          unless user.status == test["barcodes"].first["status"]
            user.update_attribute(:status, test["barcodes"].first["status"])
          end
          user.update_attributes(card_no: test["answers"].find{ |h| h["question_id"]=="8754207" }["answer"],
                                 student_id: test["answers"].find{ |h| h["question_id"]=="8693425" }["answer"])
        end
      end
    end 
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  if Rails.env == "production"
    http_basic_authenticate_with name: ENV['USER'], password: ENV['PASS']
  end
  def home
    if session[:sort].nil?
      @users = User.all
    else
      @users =User.all.send(session[:sort])
    end
  end
  def sort_by_name
    session[:sort]="sort_by_name"
    @users = User.all.send(session[:sort])
    respond_to do |format|
      format.html {render 'home'}
      format.js {}
    end
  end
  def sort_by_changed_date
    session[:sort] = "last_updated"
    @users = User.all.send(session[:sort])
    respond_to do |format|
      format.html {render'home'}
      format.js {}
    end
  end
  def sort_by_status
    session[:sort] = "sorted_by_status"
    @users = User.all.send(session[:sort])
    respond_to do |format|
      format.html {render'home'}
      format.js {}
    end
  end
  def refresh
    #User.update_db
    if session[:sort].nil?
      @users = User.all
    else
      @users = User.all.send(session[:sort])
    end
    respond_to do |format|
      format.js {}
    end
  end
  def checkin
    #@users = User.all
    #render text: "WTF"
    @user = User.find_by(card_no: params[:id])
    print "DEBUG"
    print params[:id]
    #render @user
        if @user
          if @user.status == "unused"
            @user.update_attribute(:status, "used")
            hash = {status: 200, content: @user.name}
          else
            hash = {status: 409}
          end
        else
          hash = {status: 404}
        end
        render json:hash
  end
  def live_update
    @users = User.all
  end
  def nfc
      @@nfc_context ||= NFC::Context.new
      @@nfc_device ||= @@nfc_context.open nil
      @card_content = @@nfc_device.poll
      if @card_content.class == NFC::ISO14443A
        # Get the card serial no
        @uid = @card_content.uid.collect! { |x| x.to_s(16) }.reverse!.join.to_i(16).to_s.rjust(10, "0")
        # If the card is still on the reader we skip the loop
      end
      unless @uid.nil?
        @user = User.find_by(card_no: @uid)
        if @user
          if @user.status == "unused"
            @user.update_attribute(:status, "used")
            @status = 200
          else
            @status = 409
          end
        else
            @status = 404
        end
      else
        render :status => 500
      end
      respond_to do |format|
        format.js{}
      end
  end
  def taptapfront
    @@nfc_context ||= NFC::Context.new
    @@nfc_device ||= @@nfc_context.open nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @user = User.find_by(id: params[:id])
    @users = User.all
    @count = User.all.num_of_checkins
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if session[:sort].nil?
      @users = User.all
    else
      @users = User.all.send(session[:sort])
    end
    @user.update_attribute(:status, params[:status])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
        format.js {}
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name,:email,:status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def cp(path)
        "active" if current_page?(path)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def hightlight_status(user)
		if user.status == 'unused'
			"danger"
		else
			"success"
		end
	end
end

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
      <div class = "container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "NFC BACKEND", root_path, class: "navbar-brand" %>
          </div>
        <div id="navbar" class="navbar-collapse collapse in" aria-expanded="true">
            <ul class="nav navbar-nav ">
              <li class = <%= cp(root_path) %>><%= link_to "Home", root_path %> </li>
            </ul>
          </div>
    </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ebss</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class = "container">
		<%= yield %>
</div>

</body>
</html>

app/views/static_pages/ajax.js.erb
$('#ajax').html("<%= escape_javascript(render @users).html_safe %>");

app/views/static_pages/home.html.erb
<div class = "container">
	
	<p class = "test">jQuery Test</p>
	<p>Sort By:
	<%= link_to "Name", sort_name_path, remote:true %> 
	 |
	<%= link_to "Date Edited", sort_date_path, remote:true %>
	 | 
	<%= link_to "Status", sort_status_path, remote:true %>
	 | 
	</p>
	<%= link_to "Refresh AJAX", refresh_path, class: "ajax", remote:true %>	
	<%= image_tag "ajax-loader.gif", id: "ajax-loader" %>
	<input type = "checkbox" class = "task-check">AutoRefresh</input>
	<table class = "table table-bordered table-striped table-hover">
		<tr>
			<th>Name</th>
			<th>Card Serial</th>
			<th>Student ID </th>
			<th>Status</th>
			<th>Last Updated</th>
			<th>Action</th>
		</tr>
		<tbody id = "ajax">
			<%= render @users %>
		</tbody>
	</table>
</div>
<script>
	$(document).ready(function() {
		$("#ajax-loader").hide();
    $("p.test").click(function() {
      $(this).hide();
    });
    //$(".checkin-prompt").hide();
    $(".task-check").bind('change', function(){
	  if (this.checked){
	    (function worker() {
		  $.ajax({
		    url: "<%= refresh_path %>", 
		    complete: function() {
		      // Schedule the next request when the current one's complete
		      setTimeout(worker, 5000);
		    }
		  });
		})();
	  }
}); 
  });
$(document).bind("ajaxSend", function(){
   $(".ajax").text("Loading");
   $("#ajax-loader").show();
 }).bind("ajaxComplete", function(){
   $(".ajax").text("Refresh AJAX");
   $("#ajax-loader").hide();
 });

</script>

app/views/static_pages/home.html.haml
<script>
	$(document).ready(function() {
		$("#ajax-loader").hide();
    $("p.test").click(function() {
      $(this).hide();
    });
    $(".scene").click(function() {
    	$(this).addClass("exit");
    });
    $(".task-check").bind('change', function(){
	  if (this.checked){
	    (function worker() {
		  $.ajax({
		    url: "<%= refresh_path %>", 
		    complete: function() {
		      // Schedule the next request when the current one's complete
		      setTimeout(worker, 1000);
		    }
		  });
		})();
	  }
	});
	$(".poll-nfc").bind('change', function(){
	(function worker_nfc() {
		  $.ajax({
		    url: "<%= nfc_path %>", 
		    complete: function() {
		      // Schedule the next request when the current one's complete
		      setTimeout(worker, 0);
		    }
		  });
		})(); 
	});
	$(".checkin-prompt").hide();
  });
$(document).bind("ajaxSend", function(){
   $(".ajax").text("Loading");
   $("#ajax-loader").show();
 }).bind("ajaxComplete", function(){
   $(".ajax").text("Refresh AJAX");
   $("#ajax-loader").hide();
 });

</script>

app/views/static_pages/live_update.html.erb
<div class = "container">
	<h1>Live Updates!</h1>
	<div id = "test"></div>
</div>
<script>
	$(document).ready(function(){
    setInterval(refreshDiv, 5000); 
	});
	function refreshDiv(){
	alert("Refreshing");
	$.ajax({
	  url: "http://path.to.your/webservice",
	  //other stuff you need to build your ajax request
	 }).done(function() {
	   $('test').load('/static_pages_controller/home');//update your div
	 });
	}
	(function worker() {
  $.ajax({
    url: 'ajax/test.html', 
    success: function(data) {
      $('.result').html(data);
    },
    complete: function() {
      // Schedule the next request when the current one's complete
      setTimeout(worker, 5000);
    }
  });
}	)(); 
</script>

app/views/static_pages/nfc.js.erb
<% unless @uid.nil? %>
	<% if @status == 200 %>
		 showScene($('#scene2-success'), true);
	<% elsif @status == 409 %>
		showScene($('#scene3-alreadycheckedin'), true);
	<% else %>
		showScene($('#scene4-notfound'), true);
	<% end %>
<% end %>

app/views/static_pages/refresh.js.erb
$('#ajax').html("<%= escape_javascript(render @users).html_safe %>");

app/views/static_pages/sort_by_changed_date.js.erb
$('#ajax').html("<%= escape_javascript(render @users).html_safe %>");

app/views/static_pages/sort_by_name.js.erb
$('#ajax').html("<%= escape_javascript(render @users).html_safe %>");

app/views/static_pages/sort_by_status.js.erb
$('#ajax').html("<%= escape_javascript(render @users).html_safe %>");

app/views/static_pages/taptapfront.html.erb
  <div class="scene" id="scene0-loading">
    <div class="scene-content">
      <paper>-progress{:indeterminate => ""}</paper>
    </div>
  </div>
  <div class="scene hidden" id="scene1-default">
    <div class="outer-fab">
      <div class="fab-content">
        <div class="fab-icon"></div>
        <div class="h1-buffer">
          <h1>Tap To Check In.</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="scene hidden" id="scene1a-pinging">
    <div class="outer-fab">
      <div class="fab-content">
        <div class="fab-icon">
          <paper>-spinner.paper_spinner{:active => true}</paper>
        </div>
        <div class="h1-buffer"></div>
      </div>
    </div>
  </div>
  <div class="scene temporary-scene hidden" id="scene2-success">
    <div class="outer-fab">
      <div class="fab-content">
        <div class="fab-icon"></div>
        <div class="h1-buffer">
          <h1>
            <span id="student_name"></span>
            &nbsp;
            <span id="student_id"></span>
          </h1>
        </div>
      </div>
    </div>
  </div>
  <div class="scene temporary-scene hidden" id="scene3-alreadycheckedin">
    <div class="outer-fab">
      <div class="fab-content">
        <div class="fab-icon"></div>
        <div class="h1-buffer">
          <h1>You Have Already Checked In.</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="scene temporary-scene hidden" id="scene4-notfound">
    <div class="outer-fab">
      <div class="fab-content">
        <div class="fab-icon"></div>
        <div class="h1-buffer">
          <h1>Not Found</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="scene temporary-scene hidden" id="scene5-error">
    <div class="outer-fab">
      <div class="fab-content">
        <div class="fab-icon"></div>
        <div class="h1-buffer">
          <h1>An Error Has Occured</h1>
        </div>
      </div>
    </div>
  </div>
<script>
  $(document).ready(function() {
    showScene($('#scene1-default'))
    $(".scene").click(function() {
      $(this).hide();
    });
    (function worker() {
      $.ajax({
        url: "<%= nfc_path %>",
        success: function() {
          // Schedule the next request when the current one's complete
          setTimeout(worker, 1000);
        },
        error: function() {
          setTimeout(worker, 0);
        }
      });
    })();
  });
var showScene;

showScene = function($scene, temporary) {
  if (temporary == null) {
    temporary = false;
  }
  $('.temporary-scene').hide();
  $scene.removeClass('hidden');
  if (temporary) {
    $scene.removeClass('entry exit').hide();
    clearTimeout(window["animation-timeout-" + $scene[0].id]);
    window["animation-timeout-" + $scene[0].id] = setTimeout(function() {
      return hideScene($scene);
    }, 3000);
  }
  $scene.removeClass('exit').show().addClass('entry');
  $scene.find('.outer-fab').addClass('entry');
  $scene.find('.fab-icon').addClass('entry');
  return $scene.find('h1').addClass('entry');
};

window.hideScene = function($scene) {
  return $scene.addClass('exit').delay(500).hide(0).removeClass('entry');
};

</script>

app/views/users/_form.html.erb
<%= form_for(@user, remote: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_field :name %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr class = <%= hightlight_status(user) %> >
	<td><%= user.name %></td>
	<td><%= user.card_no %></td>
	<td><%= user.student_id %></td>
	<td><%= user.status %></td>
	<td><%= user.updated_at.localtime %></td>
	<td>	
	<%= form_for user, remote:true do |f| %>
		<% if user.status == 'unused' %>
			<%= f.hidden_field :status, value: "used" %>
			<%= f.submit "Check In", class: "btn btn-success" %>
		<% else %>
			<%= f.hidden_field :status, value: "unused" %>
			<%= f.submit "Check Out", class: "btn btn-danger" %>
		<% end %>
	<% end %>
	</td>
</tr>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class = "container">
  <h1>Check-ins So Far <%= @count %> </h1>
  <div id = "notification">Notification placeholder</div>
  <table class = "table">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Status</th>
      <th>Last Updated</th>
    </tr>
    <tbody id = "ajax">
      <%= render @users %>
    </tbody>
  </table>
  <p>jQuery Test</p>
  <!-- <p><%= link_to "Refresh", update_path %></p> DEPRECATED--> 
  <p><%= link_to "Sort By Date Edited", sort_date_path %></p>
  <p><%= link_to "Sort By Status", sort_status_path %></p>
  <%= link_to "Refresh AJAX", ajax_path, class: "ajax", remote:true %>
  <div id = "loadingDiv">HEllo there guys</div>
</div>
<script>
  $(document).ready(function() {
    $.ajax({
  // your ajax code
  beforeSend: function(){
       $('.loadingDiv').show()
   },
  complete: function(){
       $('.loadingDiv').hide();
  }
});
    $("p").click(function() {
      $(this).hide();
    });   
  });
</script>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/update.js.erb
$('#ajax').html("<%= escape_javascript(render @users).html_safe %>");